sequenceDiagram
    actor User
    participant Router
    participant Blockchain
    participant Committee


    User ->> Router: Lands on domain example.com with his ID visible
    Router ->> Blockchain: Hashes the domain + ID and requests details
    Blockchain ->> Router: Returns contentRoot, trustedCommittersRoot, schemaRoot, trustedComitteeURL, statusCode 
    Router ->> Committee: I have this user ID, domain, I need the content available
    Committee ->> Router: Sends back the content, because the content is open available to user
    Router ->> User: User receives the content he asked for
